= Spearal Android

== What is Spearal?

Spearal is a compact binary format for exchanging arbitrary complex data between various endpoints such as Java EE, JavaScript / HTML, Android and iOS applications.

Spearal-Android is an extension of Spearal-Java which implements the necessary integration classes to use Spearal in Android applications.


== How to use the library?

Spearal Android provides an extension that uses the https://code.google.com/p/dexmaker[DexMaker] library to build class proxies for partial objects.

To use the library, you need to add the dependencies on Spearal-Android and on DexMaker to your project, for example in the `build.gradle` file (Android Studio):

----
dependencies {
    ...
    compile 'org.spearal:spearal-java:${spearalVersion}'
    compile 'org.spearal:spearal-android:${spearalVersion}'
    compile 'com.google.dexmaker:dexmaker:1.1'
}
----

In any other case, just download the https://github.com/spearal/spearal-java/releases[Spearal-Java] and https://github.com/spearal/spearal-android/releases[Spearal-Android] jars from github and add them to your classpath.


Then you can configure Spearal to use it with:

[source,java]
----
SpearalFactory spearalFactory = new DefaultSpearalFactory();
spearalFactory.configure(new DexMakerPartialObjectFactory());
----


== How to get and build the project?

First, you need to get, build and install Spearal-Java:

[source,bash]
----
$ git clone https://github.com/spearal/spearal-java.git
$ cd spearal-java
$ ./gradlew install
----

Then, you can build Spearal Android:

[source,bash]
----
$ cd ..
$ git clone https://github.com/spearal/spearal-android.git
$ cd spearal-android
$ ./gradlew install
----

The library can then be found in the `build/libs` directory.
